name: testabd
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  injectable: ^2.5.0
  get_it: ^8.0.3
  provider: ^6.1.1
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.2.0
#  flutter_local_notifications: ^17.0.0
#  permission_handler: ^11.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  rxdart: ^0.27.7
  iconly: ^1.0.1
  equatable: ^2.0.7
  freezed_annotation: ^2.3.2
  json_annotation: ^4.9.0
  intl_phone_field: ^3.2.0
  go_router: ^16.0.0
  dartz: ^0.10.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  http: ^1.4.0
#  view_model_x: ^1.0.0
#  carousel_slider: ^5.1.1
#  analyzer: ^5.13.0
  collection: ^1.19.1
  shimmer_animation: ^2.2.2
  #  chuck_interceptor: ^2.1.4
  pretty_dio_logger: ^1.4.0
  logger: ^2.6.2
  flutter_bloc: ^9.1.1
  web_socket_channel: ^3.0.3
  google_fonts: ^6.3.3
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.9
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4
#  flutter_native_splash: ^2.4.6


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/


#  fonts:
#    - family: Manrope
#      fonts:
#        - asset: assets/fonts/Manrope-Regular.ttf
#
#    - family: Manrope-ExtraLight
#      fonts:
#        - asset: assets/fonts/Manrope-ExtraLight.ttf
#          weight: 200
#
#    - family: Manrope-Light
#      fonts:
#        - asset: assets/fonts/Manrope-Light.ttf
#          weight: 300
#
#    - family: Manrope-Medium
#      fonts:
#        - asset: assets/fonts/Manrope-Medium.ttf
#          weight: 500
#
#    - family: Manrope-Bold
#      fonts:
#        - asset: assets/fonts/Manrope-Bold.ttf
#          weight: 700
#
#    - family: Manrope-ExtraBold
#      fonts:
#        - asset: assets/fonts/Manrope-ExtraBold.ttf
#          weight: 800
